### PR TITLE
Add support for MQTT v5.x

### PR DESCRIPTION
**Pull request by vishwamartur**
Related to #267

Add support for MQTT v5.x to the coreMQTT library.

* **manifest.yml**
  - Update `version` to "v5.0.0+".
  - Update `description` to include MQTT v5.0 support.

* **source/core_mqtt_serializer.c**
  - Add definition for MQTT protocol version 5.0.
  - Implement serialization and deserialization for MQTT v5.x packets.
  - Add handling for MQTT v5.x properties in `serializeConnectPacket`.

* **source/include/core_mqtt_config_defaults.h**
  - Add configuration option for enabling MQTT v5.x support.
  - Define `MQTT_VERSION_5_ENABLED` macro.

* **source/include/transport_interface.h**
  - Add support for MQTT v5.x in transport interface.
  - Update `TransportInterface_t` to handle MQTT v5.x packets.

### CODE REVIEW

**Comment by ActoryOu** [comment]
Hi @vishwamartur,
Thanks for your contribution! But I don't see any implementation for MQTT 5.0. Could you help check if all changes on your side are pushed to the PR?

Thank you.

**Comment by amazonKamath** [comment]
@vishwamartur we are working on MQTTv5 and here is a in progress draft PR: https://github.com/FreeRTOS/coreMQTT/pull/301 . This PR contains most of the MQTTv5 features barring subscribe and incoming publish handling.  We intend to restart work on this PR to implement the remaining feature in the next few weeks, and would appreciate contributions to that PR, rather than duplicate efforts.  Let us know if you would want to work on the PR I shared. Thanks.

**Comment by vishwamartur** [comment]
Hi @ActoryOu  and @amazonKamath ,

Thank you for the feedback! I've reviewed draft PR #301 and see the progress on MQTTv5. I'll align my contributions with the existing work to avoid duplication and help streamline the process.

If there are specific tasks or areas where you'd like me to focus, please let me know—I’ll be glad to assist in any way needed.

Thanks again!

**Comment by amazonKamath** [comment]
@vishwamartur  Thanks.  The PR#301 doesn't yet support incoming publish packets and subscribe features for v5. Any efforts in that area is welcome.  Please create any PR on top of PR#301 if you wish to contribute for MQTTv5.   Thanks.

**Comment by amazonKamath** [comment]
I am closing this PR, since we prefer to take our existing MQTTv5 implementation in PR#301.

**Pull request closed without merging**
