### PR TITLE
Use spellcheck from the CSDK repo

### PR DESCRIPTION
**Pull request by sarenameas**
Depends on: https://github.com/aws/aws-iot-device-sdk-embedded-C/pull/1212

We should not duplicate the spellcheck scripts and use the one in the CSDK repo instead.
This is an interim solution while we work on creating a separate repo for the spellcheck scripts.

### CODE REVIEW

**Comment by aggarw13** [comment]
Instead of having this repositories CI reference one of the hub-repositories (like the C-SDK), why not have a mechanism (like GitHub Actions) to monitor the duplicity of all the spell-check scripts and flag us when they differ?

**Comment by sarenameas** [comment]
> Instead of having this repositories CI reference one of the hub-repositories (like the C-SDK), why not have a mechanism (like GitHub Actions) to monitor the duplicity of all the spell-check scripts and flag us when they differ?

Because we are still repeating the scripts and they are buggy.

**Comment by nateglims** [comment]
If we could get the repo approved, I think we should put it into it's own repo as an action. We could expose a cleaner API, and (if I understand the docs correctly) it would be cached and potentially faster than cloning.

**Review by leegeth — APPROVED** [review]

**Comment by sarenameas** [comment]
> If we could get the repo approved, I think we should put it into it's own repo as an action. We could expose a cleaner API, and (if I understand the docs correctly) it would be cached and potentially faster than cloning.

A separate repo was guested by Dan, but there is a lot of process in that, so i proposed this solution next.

**Comment by nateglims** [comment]
I think this is an appropriate interim solution. Better to stop the rot now.

**Review by dan4thewin — APPROVED** [review]

**Pull request merged**
